name: CI

on: [push, pull_request]

jobs:
  testsuite:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        TYPO3: [12, 13]
        PHP: [ 8.2, 8.3 ]
        include:
          - TYPO3: 13
            php: 8.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.PHP }}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install composer dependencies TYPO3 13
        if: matrix.TYPO3 == 13
        run: |
          composer install --no-progress --no-interaction

      - name: Install composer dependencies TYPO3 12
        if: matrix.TYPO3 == 12
        run: |
          composer require typo3/cms-backend:^12.4 --no-progress --no-interaction --dev -W

      - name: Phpstan
        run: .Build/bin/phpstan analyze -c Build/phpstan.neon

      - name: Phpcsfix
        if: matrix.PHP != 8.4
        run: .Build/bin/php-cs-fixer fix --config=Build/php-cs-fixer.php --dry-run --stop-on-violation --using-cache=no
